name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    name: Linting and Unit Tests
    runs-on: ubuntu-latest

    env:
      UV_SYSTEM_PYTHON: "1"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          python-version-file: "pyproject.toml"

      - name: Install requirements
        run: uv sync --all-extras

      - name: Lint code
        run: uv run pre-commit run --all-files

      - name: Run tests
        run: uv run pytest tests
